services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: values_db
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    image: php:8.2-cli
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >-
      /bin/sh -c "apt-get update
      && apt-get install -y git unzip zip libzip-dev curl
      && docker-php-ext-configure zip
      && docker-php-ext-install zip pdo_mysql
      && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      && composer install
      && php -S 0.0.0.0:8080 -t public"
    expose:
      - "8080"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    working_dir: /app
    environment:
      - PORT=3000
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs/river.pem:/etc/ssl/certs/river.pem:ro
      - /etc/ssl/certs/river.key:/etc/ssl/certs/river.key:ro
    ports:
      - "80:80"
      - "443:443"
volumes:
  db_data:
