services:
  backend:
    image: php:8.1-cli
    working_dir: /app
    volumes:
      - ./backend:/app
    command: php -S 0.0.0.0:8001 -t .
    restart: always
    expose:
      - "8001"

  frontend:
    build: ./frontend
    working_dir: /app
    environment:
      - PORT=3000
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs/river.pem:/etc/ssl/certs/river.pem:ro
      - /etc/ssl/certs/river.key:/etc/ssl/certs/river.key:ro
    ports:
      - "80:80"
      - "443:443"
