version: '3.8'
services:
  backend:
    image: php:8.1-cli
    working_dir: /app
    volumes:
      - ./backend:/app
    command: php -S 0.0.0.0:8000 -t public
    expose:
      - "8000"

  frontend-build:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build"

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend-build
    volumes:
      - ./frontend/build/client:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"

