services:
  backend:
    image: php:8.1-cli
    working_dir: /app
    volumes:
      - ./backend:/app
    command: php -S 0.0.0.0:8000 -t .
    expose:
      - "8000"

  frontend:
    build: ./frontend
    working_dir: /app
    environment:
      - PORT=3000
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
