CREATE TABLE IF NOT EXISTS value_bins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    value VARCHAR(255) NOT NULL,
    bin TINYINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clusters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cluster_values (
    cluster_id INT NOT NULL,
    value VARCHAR(255) NOT NULL,
    PRIMARY KEY (cluster_id, value),
    CONSTRAINT fk_cluster FOREIGN KEY (cluster_id)
        REFERENCES clusters(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS value_prompts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    q1 TEXT NOT NULL,
    q2 TEXT NOT NULL,
    q3 TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS value_refinements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cluster_index INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    q1 TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
