name: Deploy to river box
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      - name: Run deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: deploy.the-still-river.com 
	  port: 22
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            bash ~/values/deploy.sh

